import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import cn from "@/utils/cn";

const poppins = Poppins({
  subsets: ["latin", "devanagari", "latin-ext"],
  weight: ["200", "400", "900"],
  style: "normal",
});

export const metadata: Metadata = {
  title: "Porfolio",
  description: "Generated by create next app",
  icons: "/logo.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(poppins.className, "bg-primary")}>{children}</body>
    </html>
  );
}
